#my aliases

# some ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# virtual python environments
alias nucastro='source ~/python-venv/nucastro/bin/activate'
alias bblog='source ~/python-venv/bblog/bin/activate'
alias ihpcss='source ~/python-venv/ihpcss/bin/activate'

# connect 2nd monitor
alias con-hdmi='swaymsg output "eDP-1" pos 0 0; swaymsg output "HDMI-A-1" pos 1920 0'
alias con-hdmi-above='swaymsg output "eDP-1" pos 0 0; swaymsg output "HDMI-A-1" pos 0 1200'

#connect headphone
alias con-phones='bluetoothctl connect 14:3F:A6:34:58:E3'
alias con-ohm='bluetoothctl connect C8:84:47:27:C5:25'
alias discon-phones='bluetoothctl disconnect'
alias discon-ohm='bluetoothctl disconnect'
alias pavucontrol='pwvucontrol'

# hop(ssh) into machines
alias cori='ssh -X -l biboyd cori.nersc.gov'
alias alcyone='ssh -l biboyd alcyone.iacs.stonybrook.edu'
alias electra='ssh -l biboyd electra.iacs.stonybrook.edu'
alias fleetwood='ssh -Yl biboyd fleetwood.astro.sunysb.edu'
alias vulcan='ssh -Yl bbrendan vulcan.astro.sunysb.edu'
alias uhura='ssh -Yl bbrendan uhura.astro.sunysb.edu'
alias bridges2='ssh -p 2222 biboyd@bridges2.psc.edu'
alias perlmutter='ssh -Yl biboyd perlmutter-p1.nersc.gov'

alias fleetwood-jupyter='ssh -NfL 8890:localhost:8890 fleetwood;firefox localhost:8890'


# wifi shortcuts
alias scan-wifi='nmcli d wifi'
alias connect-wifi='nmcli --ask d wifi connect'
