#my aliases

# some ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# virtual python environments
alias nucastro='source ~/python-venv/nucastro/bin/activate'
alias bblog='source ~/python-venv/bblog/bin/activate'

# connect 2nd monitor
alias con-vga='xrandr --output DP-1 --auto --right-of eDP-1'
alias con-hdmi='xrandr --output HDMI-1 --auto --right-of eDP-1'
alias discon-monitor='xrandr --auto'

#connect headphone
alias con-phones='bluetoothctl connect 14:3F:A6:34:58:E3'
alias discon-phones='bluetoothctl disconnect'

#Scan for wifi
alias con-wifi='iwctl station wlan0 scan'

# hop(ssh) into machines
alias cori='ssh -Y -l biboyd cori.nersc.gov'
alias alcyone='ssh -l biboyd alcyone.iacs.stonybrook.edu'
alias electra='ssh -l biboyd electra.iacs.stonybrook.edu'
