#my aliases

# some ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# virtual python environments
alias nucastro='source ~/python-venv/nucastro/bin/activate'
alias bblog='source ~/python-venv/bblog/bin/activate'
alias ihpcss='source ~/python-venv/ihpcss/bin/activate'

# wrapper aliases
alias nvvp="$HOME/Repo/config_files/wrappers/nvvp_wrapper.sh"

#simple command aliases
alias code='codium'

# connect 2nd monitor
alias con-vga='xrandr --output DP-1 --auto --right-of eDP-1'
alias con-hdmi='xrandr --output HDMI-1 --auto --right-of eDP-1; pactl set-card-profile alsa_card.pci-0000_00_1f.3 output:hdmi-stereo+input:analog-stereo'
alias con-hdmi-no-sound='xrandr --output HDMI-1 --auto --right-of eDP-1'
alias discon-monitor='xrandr --auto; pactl set-card-profile alsa_card.pci-0000_00_1f.3 output:analog-stereo+input:analog-stereo'

#connect headphone
alias con-phones='bluetoothctl connect 14:3F:A6:34:58:E3'
alias con-ohm='bluetoothctl connect C8:84:47:27:C5:25'
alias discon-phones='bluetoothctl disconnect'
alias discon-ohm='bluetoothctl disconnect'

#Scan for wifi
alias con-wifi='iwctl station wlan0 scan'

# hop(ssh) into machines
alias cori='ssh -X -l biboyd cori.nersc.gov'
alias alcyone='ssh -l biboyd alcyone.iacs.stonybrook.edu'
alias electra='ssh -l biboyd electra.iacs.stonybrook.edu'
alias fleetwood='ssh -Yl biboyd fleetwood.astro.sunysb.edu'
alias vulcan='ssh -Yl bbrendan vulcan.astro.sunysb.edu'
alias uhura='ssh -Yl bbrendan uhura.astro.sunysb.edu'
alias bridges2='ssh -p 2222 biboyd@bridges2.psc.edu'
alias perlmutter='ssh -Yl biboyd perlmutter-p1.nersc.gov'
